channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake>=3.9.0
  - python=3.7
  - pip
  - biopython
  - seqkit 
  - wget 
  - sra-tools
  - blast
  - gcc
  - pip:
    - matplotlib>3.3.2
    - pandas
    - tmhmm.py